export { SketchEditor } from './SketchEditor'
export type { SketchEditorProps } from './SketchEditor'

export { SketchModel, DEFAULT_GRID_SPACING } from './domain/SketchModel'
export type { SketchModelJSON, SketchModelInit, SketchPlane } from './domain/SketchModel'
export * from './domain/SketchEntity'
export * from './domain/Constraint'
export * from './domain/builders'
export * from './domain/geometry'
export * from './domain/hitTest'
export * from './domain/intersections'
export * from './domain/query'
export * from './domain/transform'

export { SketchRenderer, SKETCH_COLORS, formatDimension, formatNumber } from './renderer/SketchRenderer'
export type { DimensionLabel, PreviewShape, RenderOptions } from './renderer/SketchRenderer'
export * from './renderer/view'
export { SnapSystem } from './snapping/SnapSystem'
export type { SnapCandidate, SnapOptions, SnapType } from './snapping/SnapSystem'

export { SketchHistory, restoreModel } from './history'
export { describeEntity } from './entityProperties'
export type { EntityDescription, EntityProperty } from './entityProperties'

export * from './tools/SketchTool'
export { SKETCH_TOOLS, createTool, toolDefinition } from './tools/registry'
export type { ToolDefinition, ToolOption } from './tools/registry'
export { SelectTool } from './tools/SelectTool'
export { LineTool } from './tools/LineTool'
export { CircleTool } from './tools/CircleTool'
export { ArcTool } from './tools/ArcTool'
export { RectangleTool } from './tools/RectangleTool'
export { SlotTool } from './tools/SlotTool'
export { PolygonTool } from './tools/PolygonTool'
export { EllipseTool } from './tools/EllipseTool'
export { SplineTool } from './tools/SplineTool'
export { TrimTool } from './tools/TrimTool'
export { FilletTool } from './tools/FilletTool'
export { ChamferTool } from './tools/ChamferTool'
export { DimensionTool } from './tools/DimensionTool'
export { MirrorTool } from './tools/MirrorTool'
export { PatternTool } from './tools/PatternTool'
export { OffsetTool } from './tools/OffsetTool'
